version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
      args:
        NODE_ENV: development
    command: npm run express
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000

  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile