version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    expose:
      - '3306'
    env_file:
      - secrets/secrets.env

  app:
    build:
      context: .
      dockerfile: app-dev.Dockerfile
    # this is used only for dev needs
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - secrets/secrets.env
    depends_on:
      - mysql
